url: https://www.aristotlemetadata.com
permalink: blog/:categories/:year/:month/:slug.html

pagination: 
  enabled: true
  per_page: 12
  permalink: :num/
  sort_reverse: true
  trail: 
    before: 2
    after: 2

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2

sass:
    sass_dir: ./_scss

navigation:
  - title: Pricing
    url: /cloud.html
  - title: Case Studies
    url: /case_studies
  - title: Features
    url: /features
#    submenu:
#      - title: Features
#        url: /features
#      - title: Enterprise Community
#        url: /enterprise
#      - title: Cloud Hosting
#        url: /cloud
#      - title: Consulting
#        url: /contact
#   - title: Community
#     url: /community
  - title: Blog
    url: /blog/
  - title: About
    url: /about


authors:
  sam:
    display_name: Sam Spencer
    short_name: Sam
    headshot: /aristotle/images/people/legostormtroopr.md.png
    email: sam@aristotlemetadata.com
    linkedin: in/legostormtroopr
    github: legostormtroopr
    position: CEO & Co-founder
    short_about: >
        CEO and technical co-founder, Sam is the lead architect behind the Aristotle Metadata Registry
  larrn:
    display_name: Lauren Eickhorst
    short_name: Lauren
    headshot: /aristotle/images/people/larrn.md.png
    email: lauren@aristotlemetadata.com
    github: larrn
    linkedin: in/laureneickhorst
    position: COO & Co-founder
    short_about: >
        Marketing and communications coordinator.
  dylan:
    display_name: Dylan Silke
    short_name: Dylan
    headshot: /aristotle/images/people/dylan.md.jpg
    position: Full-stack developer
    short_about: >
        Aristotle Metadata Registry Developer.
  francisco:
    display_name: Francisco Gallardo 
    short_name: Francisco
    headshot: /aristotle/images/people/francisco_profile_pic.jpeg
    position: Full-stack developer
    linkedin: in/francisco-gallardo-cervantes-5a55822a
    short_about: >
        Aristotle Metadata Registry Developer.
  aristotle:
    display_name: Aristotle Devops Team
    short_name: Aristotle
    headshot: /aristotle/images/people/aristotle.256.png
    email: hello@aristotlemetadata.com
    linkedin: /company/aristotle-metadata-registry
    github: aristotle-metadata-enterprises


plans:
  registry:
    plans:
      -    
          name: Micro
          price: 2
          description: Ideal plans for organisations starting their metadata management journey.
      -
          name: Mini
          price: 4
          description: Cost-effective shared autoscaling servers with application layer security.
      -
          name: Small
          price: 7
          description: Ideal for smaller enterprises 
      -
          name: Medium
          price: 12
          popular: yes
          description: Excellent for organisations 
      -
          name: Large
          price: 20
          description: Perfect for large organisations with complex data governance
    features:
      -
          group: "Usage"
          subfeatures:
              -
                  name: Included Users
                  plans:
                      micro: 25
                      mini: 50
                      small: 100
                      medium: 250
                      large: 500
              -
                  name: Metadata storage
                  plans:
                      {micro: '20,000', mini: '50,000', small: Unlimited, medium: Unlimited, large: Unlimited}
              -
                  name: Separate organisations
                  link: organisations
                  plans:
                      {micro: no, mini: no, small: 5, medium: 10, large: Unlimited}

      -
          group: "Registry features"
          subfeatures:
              -
                  name: ISO-11179 Metadata Registry
                  plans: {micro: yes, mini: yes, small: yes, medium: yes, large: yes}
              -
                  name: Data Registry
                  plans: {micro: yes, mini: yes, small: yes, medium: yes, large: yes}
              -
                  name: Business Glossary
                  plans: {micro: yes, mini: yes, small: yes, medium: yes, large: yes}
              -
                  name: Performance Indicators
                  plans: {micro: yes, mini: yes, small: yes, medium: yes, large: yes}
              -
                  name: Ontology Management
                  plans: {micro: no, mini: no, small: yes, medium: yes, large: yes}
              -
                  name: Classifications
                  plans: {micro: no, mini: no, small: yes, medium: yes, large: yes}

      -
          group: "Help & Training"
          subfeatures:
              - 
                  name: Online Knowledge Base,<br>Video tutorials,<br>Community Forums
                  plans: {micro: yes, mini: yes, small: yes, medium: yes, large: yes}
              - 
                  name: Training sessions (per year)
                  plans: {micro: no, mini: no, small: 2, medium: 2, large: 4}
              - 
                  name: Roadmap committee representatives
                  link: roadmap
                  popover: "The Aristotle Metadata Roadmap is a annual initiative where our clients can help prioritise the delivery of new features for the Aristotle Metadata Registry"
                  tiers:
                      standard: 1 representatives
                      enterprise: 2 representatives
      -
          group: "Security"
          subfeatures:
              - 
                  name: Multi-factor Authentication (MFA)
                  plans: {micro: yes, mini: yes, small: yes, medium: yes, large: yes}
              - 
                  name: Single-sign on
                  link: secure-hosting
                  plans: {
                      micro: no, mini: no, small: no,
                      medium: {has: yes, text: "Optional addon"}, large: {has: yes, text: "Optional addon"}
                  }
              - 
                  name: Standard hosting included
                  plans: {micro: yes, mini: yes, small: yes, medium: yes, large: yes}
              - 
                  name: Aristotle Secure Hosting
                  link: secure-hosting
                  plans: {
                      micro: no, mini: no, small: no,
                      medium: {has: yes, text: "Optional addon"}, large: {has: yes, text: "Optional addon"}
                  }
              - 
                  name: Aristotle Protected Hosting
                  link: secure-hosting
                  plans: {
                      micro: no, mini: no, small: no,
                      medium: {has: yes, text: "Optional addon"}, large: {has: yes, text: "Optional addon"}
                  }